version: '3.8'

services:
  energy-agent:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DUCKDB_PATH=${DUCKDB_PATH:-data/processed/energy_2h_aggregated.duckdb}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    depends_on:
      - mcp-server

  mcp-server:
    build: .
    command: python -m mcp_server.simple_mcp_server
    environment:
      - DUCKDB_PATH=${DUCKDB_PATH:-data/processed/energy_2h_aggregated.duckdb}
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

volumes:
  data:


