name: energy-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0.0
  - polars>=0.20.0
  - duckdb>=0.9.0
  - plotly>=5.15.0
  - streamlit>=1.28.0
  - numpy>=1.24.0
  - pip
  - pip:
    - google-generativeai>=0.3.0
    - python-dotenv>=1.0.0
    - langgraph>=0.1.0


